### ISSUE TITLE
Filterbank=80

### ISSUE THREAD

**Issue by madhavsund** [jameslyons/python_speech_features#12]
It works fine for filterbank=40.But when I try for 80, the third filterbank out is constant value like this
-36.04365,-36.04365,-36.04365,-36.04365,-36.04365,-36.04365

I have attached the image showing speech,spectrogram, logfilterbank for 80 filters
![screenshot from 2015-12-03 11 13 31](https://cloud.githubusercontent.com/assets/14866815/11553006/985a4e56-99b0-11e5-9b2d-065e9cb71265.png)

**Comment by jameslyons** [comment]
I suspect this is a rounding issue based on the FFT size, if the number of filterbanks is high then there are not many FFT bins that can fit in the lower filterbanks (since they are quite narrow). I am guessing filterbank 3 has zero FFT bins in it. Try increasing the FFT size by a power of 2, if you are using nfft=512, try nfft=1024. It should fix the problem. Let me know how it goes.

**Comment by madhavsund** [comment]
Changing to 1024, solved the issue.
Thank you

**Comment by jameslyons** [comment]
no problems, glad I could help.
