### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by nikhildhar1992** [jameslyons/python_speech_features#17]
How to installl this in python

**Comment by jhoelzl** [comment]
Hi,

first make a virtual environment (http://docs.python-guide.org/en/latest/dev/virtualenvs/) in your project folder using:

```
virtualenv venv
source venv/bin/activate
```
Then clone or copy this repo in your project folder and run

```
python setup.py installl
```

After that, the command `pip list` should return speech-features.

**Comment by nikhildhar1992** [comment]
I need only that mfcc implementation code python is already installled in
my system

**Comment by jhoelzl** [comment]
When you have performed the seps above, this module is already installed and you can run `python example.py` (file.wav has to be in the same folder).

**Comment by nikhildhar1992** [comment]
In example.py it seems you have used inbuilt functions ....

**Comment by jhoelzl** [comment]
Please post your error message otherwise we can not help you.

**Comment by nikhildhar1992** [comment]
I dont have a program to run I need that code which you have explained in
http://practicalcryptography.com/miscellaneous/machine-learning/guide-mel-frequency-cepstral-coefficients-mfccs/

**Comment by jameslyons** [comment]
the python_speech_features library is the algorithm explained on that page. You have python installed, you now need to install the python_speech_features library so that you can run example.py. To install the library, download this zip file: https://github.com/jameslyons/python_speech_features/archive/master.zip

extract it somewhere. Open a terminal, cd into the directory (there should be a setup.py file in the directory). Run 'python setup.py install'.

You should then be able to run example.py

**Comment by nikhildhar1992** [comment]
thanks its  working but if I want to do all this manually
manually  in the sense ....want to implement that what u have explained
