### ISSUE TITLE
Why there's big difference using 16k and 44.1k sample rate

### ISSUE THREAD

**Issue by robotnc** [jameslyons/python_speech_features#20]
Hi:
I recorded some wav file originally in 44.1k sample rate, and then I convert this file to 16k by sox. After that I use this python script to caculate the MFCC feature of the 44.1k file and 16k file, but found that the result was completely different. And one same file no matter convert to 44.1k or 16k, I think the result should be the same. Isn't that ?

**Comment by jameslyons** [comment]
For higher sample rates you'll need more filterbanks, otherwise each filterbank will be covering a large frequency range. If you do use  more filterbanks, the higher ones will contain very little information since there is little speech info above 8khz. Sampling around 16khz should do the best.

**Comment by passarel** [comment]
Actually, this comes together with another doubt I have. I am quite concerned about the pre-emphasis function - it seems that it is a basic subtraction of the original signal by the same signal slightly delayed (multiplied by a constant near 1). This delay is considerably different depending on the frame rate (delay = (62.5 uS for fr = 16k,  24.4us for fr = 44.1).

Do you guys have any suggestion of paper or any other technical reference about this specific approach of pre-emphasis?

**Comment by jameslyons** [comment]
Preemphasis is used to 'flatten' the spectrum a little bit. For speech signals there is usually more energy in the low frequencies compared to the high frequencies.  The Preemphasis filter is a highpass filter that evens out the energy a bit. It was used a lot in the past when euclidean distances were commonly used in asr systems. With gmms or neural nets preemphasis doesn't really matter,  results will be the same whether you use it or not. It was included in the code because every other mfcc library I have seen includes it. You can safely ignore it for most purposes. Alternatively you can run some tests on a dev set with different preemph coefficients and see which, if any, works better.

**Comment by passarel** [comment]
Thanks, James... Your response was really helpful

**Comment by jameslyons** [comment]
No problem, glad I could help
