### ISSUE TITLE
Inverse MFCC to signal and rate

### ISSUE THREAD

**Issue by WeiJenLee** [jameslyons/python_speech_features#44]
Hi,

Thanks for your code. However, I have some questions. I tried to use machine learning to remove noise from a audio file, and I used MFCC as my feature. My goal is to use these feature as input data and get another MFCC matrix as my output data, and that through that matrix I can get a new signal.

My first question is,
Through MFCC, I got 39 feature in each frame, and this feature dimensions seems to be too small. What else feature could I add?

My second question is,
How could I get signal from MFCC matrix?

Lookforward for your response. Thanks!

**Comment by jameslyons** [comment]
inverting mfccs is possible, i have done it before. there is matlab code
for it here: http://www.ee.columbia.edu/ln/rosa/matlab/rastamat/ . you
basically just invert the steps used to create the mfccs, however the
result does not sound like clean speech, because a lot of information is
discarded. You can have a look at linear prediction coefficients, they are
easier to invert if you keep the residual. If you want clean speech it
would be better to look at existing speech enhancement algorithms such as
ephraim and malah MMSE.

If you are set on enhancing MFCCs, perhaps see if you can improve speech
recognition results instead of trying to recreate clean audio.
