### ISSUE TITLE
MFCC extraction using Hann window

### ISSUE THREAD

**Issue by radmar10** [jameslyons/python_speech_features#45]
Hi, could you please add an example how to use python_speech_features.base.mfcc with winfunc=Hann (or other window)?
Thank you

**Comment by jameslyons** [comment]
Use winfunc=numpy.hamming, winfunc=numpy.hanning etc. I'll add an example
to the docs

On 28 Jul 2017 7:37 PM, "radmar10" <notifications@github.com> wrote:

Hi, could you please add an example how to use python_speech_features.base.mfcc
with winfunc=Hann (or other window)?
Thank you

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jameslyons/python_speech_features/issues/45>, or mute
the thread

**Comment by jameslyons** [comment]
I just added a line to the docs for each feature type about how to use numpy windows e.g. winfunc=np.hamming

hopefully it's a bit clearer in future, thanks.
