### ISSUE TITLE
Duplicate operations, ineficient implementation for power spectrum (np.square after np.absolute)

### ISSUE THREAD

**Issue by radmar10** [jameslyons/python_speech_features#46]
Hi, I was looking in the source code and I saw that  pspec = sigproc.powspec(frames,nfft)  (power spectrum) from def fbank(...) is using numpy.absolute and then numpy.square. In this way you perform a sqrt followed by a square operation!  
More efficient would be to extract the power spectrum using directly the formula Real * Real + Imag * Imag or something similar.

**Comment by jameslyons** [comment]
Hi radmar, i tried doing np.square(np.real(complex_spec)) + np.square(np.imag(complex_spec)) instead of np.square(np.absolute(complex_spec)) but the former was slightly slower in the (limited) testing I did. If there is no clear advantage I'd rather not change it as it would result in a bit of duplicated logic. If you can come up with something that is significantly faster when you profile it, feel free to send a pull request.
